### ISSUE TITLE
[PE-D] View command inconvenient to view info

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F12-2/tp#197]
![0LPR7WBL~L__@XU`FMXW))J.png](https://raw.githubusercontent.com/WuaaAj/ped/main/files/f8689cda-da4b-4bd8-a3b7-e78fdeb5d551.png)

When view command is called, all other applicant still remain in the list. 
I think should be better to just show that single person in the list, or make the page down to that person's position.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: WuaaAj/ped#7

**Comment by jackgugz** [comment]
Major interface change shouldn't be in V1.4 though it appears to be a minor issue.
