### ISSUE TITLE
UG check 

### ISSUE THREAD

**Issue by jackgugz** [AY2122S1-CS2103T-F12-2/tp#242]
- [x] Chuan Hao
- [x] Guguz
- [x] Jerome
- [x] Nicole
- [ ] Yunpeng

**Comment by nicolej2122** [comment]
Maybe the Specification of Fields section can be moved to the top of the UG

**Comment by yunpeng1234** [comment]
FAQ Computer should be lower case

**Comment by jackgugz** [comment]
![image](https://user-images.githubusercontent.com/75773252/140610849-cc127bd5-9f3d-4acd-9499-670d259b1a8c.png)
The above part shows normal on web but we open it on github as a md file

**Comment by jackgugz** [comment]
* Need to update the download link to release 1.4 instead of 1.3
* Quick start 4: `Double-click the file to start the app. The GUI similar to the below should appear in a few seconds. Note how the app contains some sample data.` but no picture is shown
* features 2: Looks wrong on many aspects: 1. n/NAME 2. s/Friend
![image](https://user-images.githubusercontent.com/75773252/140611279-be985021-4bd8-4613-b56a-0fe6ad48dad0.png)
* filter: filter will show applicants that matches all fields specified. should be "that match"
* filter: applicants with their field containing  change to applicants with their job field containing
* edit: the "Edits" should be uncapitalised "edits"
![image](https://user-images.githubusercontent.com/75773252/140611649-bd7f6e09-2ca8-4988-a5b9-ff6ea12d3a37.png)
* edit: `filter a/APPLIED followed by edit ALL a/INTERVIEWED Updates all applicants with INTERVIEWED application status to have the ACCEPTED APPLICATION_STATUS`. change to `filter a/APPLIED followed by edit ALL a/INTERVIEWED Updates all applicants with APPLIED application status to have the INTERVIEWED APPLICATION_STATUS`.
![image](https://user-images.githubusercontent.com/75773252/140611729-6775b685-3ab5-43a2-9440-89f9d3fe28f6.png)
* command summary: add: [s/SKILL]…++ should be single +
* command summary : filter: [j/JOB] [a/STATUS] should be[j/JOB] …+ [a/STATUS]…+
* command summary: edit: edit ALL should be edit [ALL]
* command summary: suggest to split edit and edit ALL commands

**Comment by yunpeng1234** [comment]
> The above part shows normal on web but we open it on github as a md file

This for their linking thing on their website

Ill merge CH UG update and reopen new PR @jackgugz @Chang-CH

**Comment by jackgugz** [comment]
> > The above part shows normal on web but we open it on github as a md file
> 
> This for their linking thing on their website
> 
> Ill merge CH UG update and reopen new PR @jackgugz @Chang-CH

Please hold on, we have other comments left unattended to

**Comment by Jeromesyl** [comment]
- Line 11: Small grammar problem. 
- Quick start 2: Change `*.jar` to `internwatcher.jar`
- Quick start 5: "...press the Enter key..." might be more specific then "...press Enter..."
- Line 35: "Adds an applicant named `John` **with the above details**" might also be more specific
- Adding an applicant: Can include extra point for undo: If you made a mistake when adding an applicant and would like to rectify it, please use the Edit or Undo command.
- Editing applicants: Similar to the above. 
- Deleting applicants: Similar to the above.
- Line 242: Minor typo.
- APPLICATION_STATUS field is referred to as STATUS in some parts.
