### ISSUE TITLE
UG incorrect file path

### ISSUE THREAD

**Issue by Chang-CH** [AY2122S1-CS2103T-F12-2/tp#248]
UG states that `Intern Watcher saves data as a JSON file [JAR file location]/data/internwatcher.json.`

Might have to check DG etc. too

![image](https://user-images.githubusercontent.com/37036869/140600145-a0dfbb53-6b51-41c0-bfaf-1ad03690be65.png)

**Comment by yunpeng1234** [comment]
Mine saves as data/internwatcher.json
